# Generated by Django 5.1 on 2024-08-12 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_test_testvers2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestVers2',
        ),
    ]
